apiVersion: v1
description:
  The easy, open source way for everyone in your company to ask questions
  and learn from data.
name: metabase
version: 2.16.11
appVersion: latest
maintainers:
  - name: lolsborn
    email: steven@casemark.com
home: http://www.metabase.com/
icon: http://www.metabase.com/images/logo.svg
sources:
  - https://github.com/metabase/metabase
